# Generated by Django 6.0.1 on 2026-02-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='analytics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='warnings',
            field=models.JSONField(default=list),
        ),
    ]
